#!/bin/sh
# https://www.linode.com/docs/applications/remote-desktop/install-vnc-on-ubuntu-16-04/
# Uncomment the following two lines for normal desktop:
# unset SESSION_MANAGER
# exec /etc/X11/xinit/xinitrc

[ -x /etc/vnc/xstartup ] && exec /etc/vnc/xstartup
[ -r $HOME/.Xresources ] && xrdb $HOME/.Xresources
# xsetroot -solid grey
xsetroot -solid black
vncconfig -iconic &
# x-terminal-emulator -geometry 80x24+10+10 -ls -title "$VNCDESKTOP Desktop" &
x-window-manager &
# mate-session &

# gnome-panel &
# gnome-settings-daemon &
# metacity &
nautilus &
yakuake &
