---
# tasks file for vncserver_inst

- name: "apt cache update"
  apt: "update_cache=True"
  become: yes
  failed_when: False

#deprecated
# - name: "apt soft install"
  # apt: "name={{ item }} state=present"
  # become: yes
  # with_items:
  #   - vnc4server
  #   - whois
  #   - sudo

- name: "apt soft install"
  become: yes
  apt:
    # name: ['vnc4server', 'whois', 'sudo']
    # sudo apt-get install mate-desktop-environment-extras caja*
    name: ['vnc4server', 'whois', 'sudo', 'mate-desktop-environment-extras', 'caja*']

# in case scratch installed server - need some X erver e.g. light xfce4
# apt-get install xfce4 xfce4-goodies tightvncserver

# adduser vnc
# gpasswd -a vnc sudo

- name: Create a login user
  become: yes
  user:
    name: vnc
    # mkpasswd --method=sha-512 vnc
    password: '$6$Wy8VV3fa$EIaBNv9m.w1Amu47hunHHxKMse2ewDXxkM4UIP4upFmYJPclpfOaMaXtc0K65Z9Vp2l6NTXisHiO8YMl7qd4e.'
    groups:
      - sudo
      # - docker
    state: present
    shell: /bin/bash       # Defaults to /bin/bash
    system: no             # Defaults to no
    createhome: yes        # Defaults to yes
    home: /home/vnc  # Defaults to /home/<username>
    # system: yes             # Defaults to no
    # createhome: no        # Defaults to yes

# mkdir -p /usr/local/bin

# cp vncsrv /usr/local/bin/vncsrv

# sudo chown vnc:vnc /usr/local/bin/vncsrv
# sudo chmod +x /usr/local/bin/vncsrv

- name: Copy file with owner and permissions
  become: yes
  copy:
    src: vncsrv
    dest: /usr/local/bin/vncsrv
    owner: vnc
    group: vnc
    mode: 'a+x'

- name: Copy passwd file with owner and permissions
  become: yes
  copy:
    src: passwd
    dest: /home/vnc/.vnc/passwd
    owner: vnc
    group: vnc
    mode: '0600'

- name: Copy xstartup file with owner and permissions
  become: yes
  copy:
    src: xstartup
    dest: /home/vnc/.vnc/xstartup
    owner: vnc
    group: vnc
    mode: '0755'

# - name: Copy xstartup file with owner and permissions
#   become: yes
#   copy:
#     src: xstartup
#     # dest: /etc/xstartup
#     dest: /tmp/xstartup
#     owner: vnc
#     group: vnc
#     mode: '0755'


# - name: debug xstartup
#   become: yes
#   shell: "whoami ; ls -ali /etc/xstartup ; cat /etc/xstartup"
#   # shell: "whoami ; ls -ali /tmp/xstartup ; cat /tmp/xstartup"
#   register: vncsrv_status

# - debug:
#     # msg: "{{ vncsrv_status.stdout }}"
#     msg: "{{ vncsrv_status.stdout_lines }}"

# cp vncsrv.service /lib/systemd/system/vncsrv.service
- name: Copy file with owner and permissions
  become: yes
  copy:
    src: vncsrv.service
    dest: /lib/systemd/system/vncsrv.service
    # owner: vnc
    # group: vnc
    # mode: 'a+x'

# sudo systemctl enable vncsrv.service
# sudo systemctl -l status vncsrv.service
# sudo systemctl daemon-reload

- name: start vncsrv
  become: yes
  systemd:
    state: started
    name: vncsrv
    enabled: yes
    daemon_reload: yes
  register: vncsrv_status

- debug:
    msg: "{{ vncsrv_status.status }}"
    # msg: "{{ vncsrv_status.stdout_lines }}"

- name: list systemd
  become: yes
  command: "systemctl -l status vncsrv.service"
  register: vncsrv_status
  ignore_errors: yes
# Use xtigervncviewer -SecurityTypes VncAuth -passwd /root/.vnc/passwd :2 to connect to the VNC server.

- debug:
    # msg: "{{ vncsrv_status.stdout }}"
    msg: "{{ vncsrv_status.stdout_lines }}"

- name: debug netstat ports
  become: yes
  shell: "netstat -plan | grep -i vnc"
  register: vncsrv_status
  failed_when: false
  changed_when:
    - vncsrv_status.rc <= 1
  # shell: "netstat -nltp | grep vnc"
  # command: "netstat -plan | grep vnc"

- debug:
    # msg: "{{ vncsrv_status.stdout }}"
    msg: "{{ vncsrv_status.stdout_lines }}"

- name: debug ps -aux
  become: yes
  shell: "ps -aux | grep -i vnc"
  register: vncsrv_status
  ignore_errors: yes

- debug:
    # msg: "{{ vncsrv_status.stdout }}"
    msg: "{{ vncsrv_status.stdout_lines }}"

#----
- name: STOP VNC server for vnc user
  become: yes
  shell: "sudo -u vnc vncsrv stop"
  register: vncsrv_status
  ignore_errors: yes

- name: REstart vncsrv
  become: yes
  systemd:
    state: restarted
    name: vncsrv
    enabled: yes
    daemon_reload: yes
  register: vncsrv_status

#----

- name: RUN VNC server for vnc user
  become: yes
  shell: "sudo -u vnc vncsrv start "
  register: vncsrv_status
  ignore_errors: yes

- debug:
    # msg: "{{ vncsrv_status.stdout }}"
    msg: "{{ vncsrv_status.stdout_lines }}"

- name: LOG VNC server for vnc user
  become: yes
  shell: "tail -n 30 /home/vnc/.vnc/usrv:2.log"
  register: vncsrv_status
  ignore_errors: yes

- debug:
    # msg: "{{ vncsrv_status.stdout }}"
    msg: "{{ vncsrv_status.stdout_lines }}"

- debug:
    msg: "Please USE now:\
sh vnc@usrv -L 5902:localhost:5902 \
-> KRDC \
localhost:5902 + vnc password \
"