---
# tasks file for vncserver_inst

- name: "apt cache update"
  apt: "update_cache=True"
  become: yes
  failed_when: False

- name: "apt soft install"
  apt: "name={{ item }} state=present"
  become: yes
  with_items:
    - python-setuptools
    - python-pip

