---
# tasks file for vncserver_inst

# - name: "apt cache update"
#   become: yes
#   shell: "echo 'add VirtualBox repository:' \
# wget -q https://www.virtualbox.org/download/oracle_vbox_2016.asc -O- | sudo apt-key add - && \
# wget -q https://www.virtualbox.org/download/oracle_vbox.asc -O- | sudo apt-key add - && \
# echo 'added sUCCESSFULLY!!!'"

#   # failed_when: False

# wget -q https://www.virtualbox.org/download/oracle_vbox_2016.asc -O- | sudo apt-key add -
# wget -q https://www.virtualbox.org/download/oracle_vbox.asc -O- | sudo apt-key add -

- name: config 3rd party repos for VirtualBox
  become: yes
  block:
    #----------------------------------
    #MS VS Code
    #----------------------------------
    # https://linuxize.com/post/how-to-install-visual-studio-code-on-ubuntu-18-04/
    # wget -q https://packages.microsoft.com/keys/microsoft.asc -O- | sudo apt-key add -
    # sudo add-apt-repository "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main"
    # sudo apt update
    # sudo apt install code

    # always try to use HTTPS. I'm not sure why the nginx folks don't provide it.
    - name: add Oracle VirtualBox2016 apt-key (Legacy)
      apt_key:
        url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
        state: present
      # when: linux_old is defined and linux_old
    - name: add Oracle VirtualBox apt-key
      apt_key:
        url: https://www.virtualbox.org/download/oracle_vbox.asc
        state: present

    #replaced by command below
    # - name: add MS VS Code apt repository
    #   become: yes
    #   apt_repository:
    #     # repo: 'deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main'
    #     # repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
    #     repo: deb https://packages.microsoft.com/repos/vscode stable main
    #     state: present
    #     # filename: msvscode
    #     # update_cache: yes

    - name: add Oracle VirtualBox add-apt-repository
      become: yes
      command: add-apt-repository "deb [arch=amd64] https://download.virtualbox.org/virtualbox/debian eoan contrib"
      # when: linux_old is defined and linux_old
    # sudo add-apt-repository "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main"

    - name: "apt cache update"
      apt: "update_cache=True"
      become: yes
      failed_when: False

    - name: "apt soft install"
      become: yes
      apt:
        # name: ['vnc4server', 'whois', 'sudo']
        # sudo apt-get install mate-desktop-environment-extras caja*
        name: ['virtualbox', 'vagrant']
        # name: ['virtualbox-6.1'] # IS NOT COMPATIBLE with vagrant 2.2.3 (probably up to 2.2.6 too)

# Could error with
# virtualbox-dkms set to manually installed.
# linux-headers-generic is already the newest version (5.3.0.24.28).
# may be install manually
# OR reboot host and try again

    - name: "apt soft temporary remove"
      become: yes
      apt:
        state: absent
        name: ['vagrant-libvirt']

# vagrant plugin install vagrant-disksize vagrant-vbguest
    - name: add vagrant plugins
      become: yes
      command: vagrant plugin install vagrant-disksize vagrant-vbguest
      # when: linux_old is defined and linux_old

    # - name: "apt soft back after temporary remove"
    #   become: yes
    #   apt:
    #     state: present
    #     name: ['vagrant-libvirt']

vboxusers - add to this group necessary users!

####################################
# CONFIGURATION #
# /mnt/zfs05tb_kvm/vbox
# VM STORAGE
# https://www.virtualbox.org/manual/ch08.html#vboxmanage-setproperty
# VBoxManage setproperty
# This command is used to change global settings which affect the entire Oracle VM VirtualBox installation. Some of these correspond to the settings in the Global Settings dialog in the graphical user interface. The following properties are available:
# machinefolder
#     Specifies the default folder in which virtual machine definitions are kept. See Section 10.1, “Where Oracle VM VirtualBox Stores its Files”.

# vboxmanage list [--long|-l] [--sorted|-s]
#   vms|runningvms|ostypes|hostdvds|hostfloppies|intnets|bridgedifs|hostonlyifs|natnets|dhcpservers|hostinfo|hostcpuids|hddbackends|hdds|dvds|floppies|usbhost|usbfilters|systemproperties|extpacks|groups|webcams|screenshotformats|cloudproviders|cloudprofiles
# vboxmanage list systemproperties #for user who run this command!!!!

# vboxmanage   setproperty
#   machinefolder default|<folder> |
#   hwvirtexclusive on|off |
#   vrdeauthlibrary default|<library> |
#   websrvauthlibrary default|null|<library> |
#   vrdeextpack null|<library> |
#   autostartdbpath null|<folder> |
#   loghistorycount <value>
#   defaultfrontend default|<name>
#   logginglevel <log setting>
#   proxymode system|noproxy|manual
#   proxyurl <url>

vboxmanage setproperty machinefolder /mnt/zfs05tb_kvm/vbox


# vboxmanage
#   natnetwork                list [<pattern>]
#                             add /  remove / start / stop

# root@usrv:~/VirtualBox VMs# VBoxManage list vms
# "ubuntu1804-v0.1" {7116bece-8a7f-411d-9b89-3fd8ecd98003}

# VBoxManage controlvm ubuntu1804-v0.1 acpipowerbutton

# VBoxManage unregistervm  ubuntu1804-v0.1 --delete # delete from disk!!!!! could be skipped