---
- name: install owncloud 10s
  hosts: all # or spec group or host only
  become: yes
  roles:
    - { role: owncloud_install_local, when: ansible_system == 'Linux' }    # только если ОС линух
#    - owncloud_install_local # безусловный и безпараметричный запуск роли
# а так с параметрами
## tags: install
