---
- name: ZFS install + cfg 
  hosts: all # or spec group or host only
  become: yes
  roles:
    # - { role: owncloud_install_local, when: ansible_system == 'Linux' }    # только если ОС линух
    - { role: zfs_install_cfg }    # только если ОС линух
#    - { role: usrv_prep_soft, when: ansible_system == 'Linux' }    # только если ОС линух
#    - owncloud_install_local # безусловный и безпараметричный запуск роли
# а так с параметрами
## tags: install
